//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_PR16_clothes__Kile.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeClothes
    {
        public int ID { get; set; }
        public string naimenov { get; set; }
        public string razmer { get; set; }
        public string color { get; set; }
        public string brend { get; set; }
        public decimal cena { get; set; }
    
        public virtual BrendTable BrendTable { get; set; }
        public virtual ColorTable ColorTable { get; set; }
        public virtual RazmerTable RazmerTable { get; set; }
    }
}
