//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_PR16_clothes__Kile.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeClothesEntities : DbContext
    {
        private static HomeClothesEntities _context;
        public HomeClothesEntities()
            : base("name=HomeClothesEntities")
        {
        }

        public static HomeClothesEntities GetContext()
        {
            if (_context == null)
                _context = new HomeClothesEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BrendTable> BrendTable { get; set; }
        public virtual DbSet<ColorTable> ColorTable { get; set; }
        public virtual DbSet<HomeClothes> HomeClothes { get; set; }
        public virtual DbSet<RazmerTable> RazmerTable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
